name: semconstmining
channels:
  - conda-forge
dependencies:
  - python=3.9
  # PYTHON AND JUPYTER BASICS
  - pip=23.0
  - ipython=8.7.0
  - tqdm=4.64.1
  - joblib=1.2.0
  # DATA SCIENCE BASICS
  - pandas=1.5.3
  - numpy=1.24.1
  - matplotlib=3.6.2
  - jupyterlab
  # NLP
  - spacy=3.5.2
  - wordcloud=1.8.2.2
  - stringcase=1.2.0
  - nltk=3.8.1
  - pip:
      - -e .  # install project in editable mode
      - spacy_langdetect==0.1.2  # not available in conda-forge
      - language_data==1.1
      - transformers==4.10.3
      - pytorch-transformers==1.2.0
      - torch==1.13.1
      - six==1.16.0
      - pm4py==2.5.1
      - metric-temporal-logic==0.4.0
      - sentence_transformers==2.2.2
      - mlxtend==0.21.0
      - func-timeout==4.3.5
      - python-dotenv==1.0.0
      - gensim==4.3.1,
      - pylogics==0.1.1,
      - textblob
      - typer==0.4.2
      - typing-extensions==4.5.0,
      - func-timeout==4.3.5
